[workspace]
members = [
  "aggregator-mock",
  "aggregator-mock/abi",
  "egld-esdt-swap",
  "egld-esdt-swap/abi",
  "esdt-safe",
  "esdt-safe/abi",
  "ethereum-fee-prepay",
  "multi-transfer-esdt",
  "multi-transfer-esdt/abi",
  "multisig",
  "multisig/abi"
]
